### PR TITLE
new-LEDs-usages-&-rollergripper-optimisation

### PR DESCRIPTION
**Pull request by TapChap**
implemented LEDs blinking when using the Cuber & the Arm subsystem, 
also returned the new implementation of the Rollergripper class that was lost in the last merge

### CODE REVIEW

**Review by ExcaliburFRC6738 — APPROVED** [review]

**Comment by ExcaliburFRC6738** [comment]
@Amit-Sucher you are more then welcome to merge this PR

**Comment by Amit-Sucher** [comment]
> @Amit-Sucher You and I both missed the fact that the new implementation of the roller gripper class from a couple of weeks ago was accidentally lost in the merge of the last commit from yesterday

l

**Comment by TapChap** [comment]
what?

**Comment by TapChap** [comment]
why the heck did you close it?

**Comment by TapChap** [comment]
thanks

**Comment by Amit-Sucher** [comment]
I accidentally deleted something else lmao

**Pull request merged**
